services:
  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_c
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
    volumes:
      - ./:/app
      - ./static_volume/django_c:/app/static/django_c
      #/var/docker-shared/1_Infrastructure/static_volume/django_c:/app/static/django_c
      
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5


networks:
  postgres_network:
    external: true
