# Generated by Django 5.1 on 2024-12-22 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StrojZastojOpombaEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stroj", models.CharField(max_length=255)),
                ("artikel", models.CharField(blank=True, max_length=255, null=True)),
                ("izmena", models.IntegerField()),
                ("opomba", models.TextField(blank=True)),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
                ("zastoj_entries", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TimConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=255, unique=True)),
                ("team_label", models.CharField(max_length=255)),
                ("vodja", models.CharField(max_length=255)),
                ("ad_username", models.CharField(max_length=255)),
                ("oddelek", models.CharField(max_length=255)),
                ("obrat", models.CharField(max_length=255)),
                ("team_label_slug", models.SlugField(blank=True, max_length=255)),
                (
                    "team_name_slug",
                    models.SlugField(blank=True, max_length=255, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ime_tabele", models.CharField(max_length=255)),
                ("operacija", models.IntegerField(blank=True, null=True)),
                ("opravilo", models.IntegerField(blank=True, null=True)),
                (
                    "tim_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="definitions",
                        to="signali_strojev.timconfig",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StrojEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stroj", models.CharField(max_length=255)),
                ("postaja", models.CharField(blank=True, max_length=255, null=True)),
                ("is_delovno_mesto", models.BooleanField(default=False)),
                (
                    "tim_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stroj_entries",
                        to="signali_strojev.timdefinition",
                    ),
                ),
            ],
        ),
    ]
