# Generated by Django 5.1 on 2024-12-22 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stepper",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("project", models.CharField(max_length=255)),
                ("assigner", models.CharField(max_length=255)),
                ("assignee", models.CharField(max_length=255)),
                ("assignee_username", models.CharField(max_length=255)),
                ("loggedusername", models.CharField(max_length=255)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="steppers", to="home.usergroup"
                    ),
                ),
                (
                    "obrat_oddelek",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steppers",
                        to="home.obratioddelki",
                    ),
                ),
            ],
            options={
                "db_table": "stepper",
            },
        ),
        migrations.CreateModel(
            name="TaskStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("exp_time", models.DateTimeField()),
                ("order", models.IntegerField()),
                ("status", models.CharField(default="Queued", max_length=50)),
                ("machine", models.CharField(blank=True, max_length=255, null=True)),
                ("product", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "Nizka"), (2, "Srednja"), (3, "Visoka")], default=2
                    ),
                ),
                ("status_modified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status_modified_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stepper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="pregled_aktivnosti.stepper",
                    ),
                ),
            ],
            options={
                "db_table": "task_step",
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="pregled_aktivnosti.taskstep",
                    ),
                ),
            ],
            options={
                "db_table": "attachment",
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("action_name", models.CharField(max_length=255)),
                ("user", models.CharField(max_length=255)),
                (
                    "task_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="pregled_aktivnosti.taskstep",
                    ),
                ),
            ],
            options={
                "db_table": "action",
            },
        ),
        migrations.AddConstraint(
            model_name="stepper",
            constraint=models.UniqueConstraint(
                fields=("project", "assigner"), name="unique_project_assigner"
            ),
        ),
    ]
