# Generated by Django 5.1 on 2024-12-22 16:28

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sarza", models.CharField(max_length=100)),
                ("datum_dobave", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "del_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_inbound_blocked", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PostajeStrojevTisna0104Montaza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stroj", models.CharField(max_length=255)),
                ("opis_stroja", models.CharField(max_length=255)),
                ("postaja_stroja", models.CharField(max_length=255)),
                ("opis_postaje", models.CharField(max_length=255)),
                ("delovno_mesto", models.CharField(max_length=255)),
                ("opis_delovnega_mesta", models.CharField(max_length=255)),
                ("postaje_v_zaporedju", models.CharField(max_length=255)),
                ("paralel", models.CharField(max_length=255)),
                ("obmocje", models.CharField(blank=True, max_length=255, null=True)),
                ("rocna_montaza", models.BooleanField(default=False)),
                ("zalogovnik", models.CharField(max_length=255)),
                (
                    "production_reported_on_postaja",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "postaja_logic_used",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "postaje_strojev_tisna0104_montaza",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PreteklostZamenjavSarzTisna1160",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datum_transakcije",
                    models.DateTimeField(db_column="datum_transakcije"),
                ),
                ("seq_number", models.TextField(db_column="seq_number")),
                (
                    "zaposlen",
                    models.FloatField(blank=True, db_column="zaposlen", null=True),
                ),
                (
                    "zaposlen_ime",
                    models.TextField(blank=True, db_column="zaposlen_ime", null=True),
                ),
                ("nalog", models.BigIntegerField(db_column="nalog")),
                (
                    "pozicija",
                    models.BigIntegerField(blank=True, db_column="pozicija", null=True),
                ),
                ("del_id", models.TextField(db_column="del_id")),
                (
                    "del_opis",
                    models.TextField(blank=True, db_column="del_opis", null=True),
                ),
                ("sarza", models.TextField(db_column="sarza")),
                (
                    "dejanska_kolicina",
                    models.BigIntegerField(
                        blank=True, db_column="dejanska_kolicina", null=True
                    ),
                ),
                (
                    "zakljucena_kolicina",
                    models.FloatField(
                        blank=True, db_column="zakljucena_kolicina", null=True
                    ),
                ),
                (
                    "problem_materiala",
                    models.TextField(
                        blank=True, db_column="problem_materiala", null=True
                    ),
                ),
                ("dan", models.DateTimeField(blank=True, db_column="dan", null=True)),
            ],
            options={
                "db_table": "preteklost_zamenjav_sarz_tisna1160",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TiBOMKosovnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artikel", models.CharField(db_column="artikel", max_length=100)),
                ("opis", models.CharField(db_column="opis", max_length=255)),
                (
                    "verzija_razvojnega_artikla",
                    models.CharField(
                        db_column="Verzija razvojnega artikla", max_length=100
                    ),
                ),
                ("bom_kol", models.CharField(db_column="BOM kol", max_length=100)),
                ("pozicija", models.CharField(db_column="Pozicija", max_length=100)),
                ("del_id", models.CharField(db_column="del_id", max_length=100)),
                ("del_opis", models.CharField(db_column="del_opis", max_length=255)),
                ("kolicina", models.CharField(db_column="kolicina", max_length=100)),
                ("enota", models.CharField(db_column="enota", max_length=100)),
                ("skladisce", models.CharField(db_column="Skladišče", max_length=100)),
                ("operacija", models.CharField(db_column="Operacija", max_length=100)),
                (
                    "datum_veljavnosti",
                    models.CharField(db_column="Datum veljavnosti", max_length=100),
                ),
                (
                    "datum_preteka",
                    models.CharField(db_column="Datum preteka", max_length=100),
                ),
                ("phantom", models.CharField(db_column="Phantom", max_length=100)),
                ("besedilo", models.CharField(db_column="Besedilo", max_length=255)),
            ],
            options={
                "db_table": "tibom1110_kosovnica",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CumulativeCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artikel", models.CharField(max_length=100)),
                ("stroj", models.CharField(max_length=100)),
                ("postaja", models.CharField(max_length=100)),
                ("del_id", models.CharField(max_length=100)),
                ("sarza", models.CharField(max_length=100)),
                (
                    "cumulative_count",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=20
                    ),
                ),
            ],
            options={
                "unique_together": {("artikel", "stroj", "postaja", "del_id", "sarza")},
            },
        ),
        migrations.CreateModel(
            name="InboundVirtualBatchAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stroj", models.CharField(max_length=100)),
                ("postaja", models.CharField(max_length=100)),
                (
                    "total_inbound_quantity",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("allocated", models.BooleanField(default=False)),
                (
                    "original_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vgradni_deli.batch",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vgradni_deli.part",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InboundVirtualBatchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("virtual_sarza", models.CharField(max_length=200)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="vgradni_deli.inboundvirtualbatchallocation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InboundTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stroj", models.CharField(max_length=100)),
                ("postaja", models.CharField(max_length=100)),
                (
                    "quantity_added",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("day_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vgradni_deli.batch",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vgradni_deli.part",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="batch",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vgradni_deli.part"
            ),
        ),
        migrations.CreateModel(
            name="AdjustmentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stroj", models.CharField(max_length=100)),
                ("postaja", models.CharField(max_length=100)),
                (
                    "quantity_adjustment",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("day_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vgradni_deli.batch",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vgradni_deli.part",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stroj", models.CharField(max_length=100)),
                ("postaja", models.CharField(max_length=100)),
                ("artikel", models.CharField(max_length=100)),
                (
                    "quantity_consumed",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("day_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vgradni_deli.batch",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vgradni_deli.part",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StrojArtikelSarzaMoznosti",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stroj", models.CharField(max_length=100)),
                ("artikel", models.CharField(max_length=100)),
                ("sarza", models.CharField(max_length=100)),
                ("del_id", models.CharField(max_length=100)),
                ("nalog", models.BigIntegerField()),
            ],
            options={
                "unique_together": {("stroj", "artikel", "sarza", "del_id", "nalog")},
            },
        ),
        migrations.CreateModel(
            name="StrojArtikelSarzaTrenutno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stroj", models.CharField(max_length=100)),
                ("artikel", models.CharField(max_length=100)),
                ("sarza", models.CharField(max_length=100)),
                ("del_id", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "stroj_artikel_sarza_trenutno",
                "unique_together": {("stroj", "artikel", "del_id")},
            },
        ),
        migrations.CreateModel(
            name="ZalogaSarza",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "dobavni_nalog",
                    models.CharField(db_column="dobavni_nalog", max_length=100),
                ),
                ("del_id", models.CharField(db_column="del_id", max_length=100)),
                ("sarza", models.CharField(db_column="sarza", max_length=100)),
                (
                    "del_opis",
                    models.CharField(
                        blank=True, db_column="del_opis", max_length=255, null=True
                    ),
                ),
                ("datum_dobave", models.DateField(db_column="datum_dobave")),
                (
                    "zaloga",
                    models.DecimalField(
                        db_column="zaloga", decimal_places=2, max_digits=12
                    ),
                ),
            ],
            options={
                "db_table": "zaloga_sarza",
                "managed": True,
                "unique_together": {("dobavni_nalog", "del_id", "sarza")},
            },
        ),
        migrations.CreateModel(
            name="CurrentStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stroj", models.CharField(max_length=100)),
                ("postaja", models.CharField(max_length=100)),
                (
                    "current_stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vgradni_deli.batch",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vgradni_deli.part",
                    ),
                ),
            ],
            options={
                "unique_together": {("part", "batch", "stroj", "postaja")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="batch",
            unique_together={("sarza", "part")},
        ),
    ]
